-- V102 (seed-dev): D-13 — seed initial inventory.
--
-- LƯU Ý KIẾN TRÚC (Phase 24 — Database Per Service):
-- Bản gốc Phase 23 copy stock bằng `INSERT ... SELECT FROM product_svc.products`.
-- Sau Phase 24, mỗi service có database Postgres RIÊNG → không còn cross-database
-- query được. inventory-service không truy cập được bảng products của product-service.
--
-- inventory_items đã được seed đầy đủ cho môi trường dev bởi V2__seed_dev_data.sql
-- (prod-001..prod-010 với quantity cụ thể). V102 do đó là no-op idempotent — giữ file
-- để Flyway history nhất quán; khi cần đồng bộ stock thật giữa 2 service, dùng event
-- (RabbitMQ) hoặc API thay vì cross-DB SQL.
SELECT 1;
